/**
 * CPMC employee roster (corporate + on-site).
 * Staffing sized from 2025–2026 PM industry benchmarks; pay mid-market US.
 */

import {
  CADE_EMPLOYEE_ID,
  CADE_DEMO,
  makeCadeEmployee,
  resolveEmployeeModuleAccess,
  type HrEmployee,
} from "@/lib/hr";

type RosterSeed = {
  id: string;
  employeeId: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  department: HrEmployee["department"];
  category: HrEmployee["category"];
  jobTitle: string;
  propertyId: string;
  propertyName: string;
  payType: HrEmployee["payType"];
  /** Annual salary or hourly rate */
  payRate: number;
  payFrequency?: HrEmployee["payFrequency"];
};

const TODAY = new Date().toISOString().slice(0, 10);

/**
 * Corporate (CPMC PM co.) + property staff for the 3-asset portfolio.
 *
 * Grandview ~300 units → PM + APM + 2 leasing + maint supervisor + 3 techs + porter
 * Meridian Tower (Chicago office) → PM + chief engineer + engineer + admin + porter
 * Riverbend industrial (~24 bays) → PM + maintenance + admin/leasing
 */
export const HARBORLINE_EMPLOYEE_ROSTER: RosterSeed[] = [
  // —— Corporate (Cade preserved separately if already in DB) ——
  {
    id: CADE_EMPLOYEE_ID,
    employeeId: "HL-0001",
    firstName: "Cade",
    lastName: "Coburn",
    email: CADE_DEMO.email,
    phone: "(662) 555-0101",
    department: "management",
    category: "corporate",
    jobTitle: "Director of Operations",
    propertyId: "",
    propertyName: "CPMC Corporate",
    payType: "salary",
    payRate: 95000,
  },
  {
    id: "hr-emp-corp-controller",
    employeeId: "HL-0002",
    firstName: "Nora",
    lastName: "Ellison",
    email: "nora.ellison@cpmc.demo",
    phone: "(312) 555-0202",
    department: "accounting",
    category: "corporate",
    jobTitle: "Controller",
    propertyId: "",
    propertyName: "CPMC Corporate",
    payType: "salary",
    payRate: 108000,
  },
  {
    id: "hr-emp-corp-ap",
    employeeId: "HL-0003",
    firstName: "Marcus",
    lastName: "Chen",
    email: "marcus.chen@cpmc.demo",
    phone: "(312) 555-0203",
    department: "accounting",
    category: "corporate",
    jobTitle: "Accounts Payable Lead",
    propertyId: "",
    propertyName: "CPMC Corporate",
    payType: "salary",
    payRate: 62000,
  },
  {
    id: "hr-emp-corp-ar",
    employeeId: "HL-0004",
    firstName: "Priya",
    lastName: "Shah",
    email: "priya.shah@cpmc.demo",
    phone: "(312) 555-0204",
    department: "accounting",
    category: "corporate",
    jobTitle: "AR & Collections Lead",
    propertyId: "",
    propertyName: "CPMC Corporate",
    payType: "salary",
    payRate: 58000,
  },
  {
    id: "hr-emp-corp-hr",
    employeeId: "HL-0005",
    firstName: "Jordan",
    lastName: "Blake",
    email: "jordan.blake@cpmc.demo",
    phone: "(312) 555-0205",
    department: "hr",
    category: "corporate",
    jobTitle: "HR Generalist",
    propertyId: "",
    propertyName: "CPMC Corporate",
    payType: "salary",
    payRate: 68000,
  },
  {
    id: "hr-emp-corp-marketing",
    employeeId: "HL-0006",
    firstName: "Avery",
    lastName: "Cole",
    email: "avery.cole@cpmc.demo",
    phone: "(312) 555-0206",
    department: "leasing",
    category: "corporate",
    jobTitle: "Marketing Coordinator",
    propertyId: "",
    propertyName: "CPMC Corporate",
    payType: "salary",
    payRate: 55000,
  },
  {
    id: "hr-emp-corp-ea",
    employeeId: "HL-0007",
    firstName: "Sam",
    lastName: "Rivera",
    email: "sam.rivera@cpmc.demo",
    phone: "(312) 555-0207",
    department: "management",
    category: "corporate",
    jobTitle: "Executive Assistant",
    propertyId: "",
    propertyName: "CPMC Corporate",
    payType: "salary",
    payRate: 52000,
  },

  // —— Grandview Apartments (300-unit multifamily, Nashville) ——
  {
    id: "hr-emp-gv-pm",
    employeeId: "HL-0101",
    firstName: "Dana",
    lastName: "Whitfield",
    email: "dana.whitfield@cpmc.demo",
    phone: "(615) 555-1101",
    department: "management",
    category: "property",
    jobTitle: "Community Manager",
    propertyId: "prop-grandview",
    propertyName: "Grandview Apartments",
    payType: "salary",
    payRate: 72000,
  },
  {
    id: "hr-emp-gv-apm",
    employeeId: "HL-0102",
    firstName: "Chris",
    lastName: "Alvarez",
    email: "chris.alvarez@cpmc.demo",
    phone: "(615) 555-1102",
    department: "management",
    category: "property",
    jobTitle: "Assistant Community Manager",
    propertyId: "prop-grandview",
    propertyName: "Grandview Apartments",
    payType: "salary",
    payRate: 48000,
  },
  {
    id: "hr-emp-gv-lease-1",
    employeeId: "HL-0103",
    firstName: "Mia",
    lastName: "Brooks",
    email: "mia.brooks@cpmc.demo",
    phone: "(615) 555-1103",
    department: "leasing",
    category: "property",
    jobTitle: "Leasing Consultant",
    propertyId: "prop-grandview",
    propertyName: "Grandview Apartments",
    payType: "salary",
    payRate: 42000,
  },
  {
    id: "hr-emp-gv-lease-2",
    employeeId: "HL-0104",
    firstName: "Owen",
    lastName: "Park",
    email: "owen.park@cpmc.demo",
    phone: "(615) 555-1104",
    department: "leasing",
    category: "property",
    jobTitle: "Leasing Consultant",
    propertyId: "prop-grandview",
    propertyName: "Grandview Apartments",
    payType: "salary",
    payRate: 40000,
  },
  {
    id: "hr-emp-gv-maint-sup",
    employeeId: "HL-0105",
    firstName: "Ty",
    lastName: "Nguyen",
    email: "ty.nguyen@cpmc.demo",
    phone: "(615) 555-1105",
    department: "maintenance",
    category: "property",
    jobTitle: "Maintenance Supervisor",
    propertyId: "prop-grandview",
    propertyName: "Grandview Apartments",
    payType: "salary",
    payRate: 58000,
  },
  {
    id: "hr-emp-gv-tech-1",
    employeeId: "HL-0106",
    firstName: "Luis",
    lastName: "Ortega",
    email: "luis.ortega@cpmc.demo",
    phone: "(615) 555-1106",
    department: "maintenance",
    category: "property",
    jobTitle: "Maintenance Technician",
    propertyId: "prop-grandview",
    propertyName: "Grandview Apartments",
    payType: "hourly",
    payRate: 22,
  },
  {
    id: "hr-emp-gv-tech-2",
    employeeId: "HL-0107",
    firstName: "Keisha",
    lastName: "Ward",
    email: "keisha.ward@cpmc.demo",
    phone: "(615) 555-1107",
    department: "maintenance",
    category: "property",
    jobTitle: "Maintenance Technician",
    propertyId: "prop-grandview",
    propertyName: "Grandview Apartments",
    payType: "hourly",
    payRate: 20,
  },
  {
    id: "hr-emp-gv-tech-3",
    employeeId: "HL-0108",
    firstName: "Ben",
    lastName: "Holt",
    email: "ben.holt@cpmc.demo",
    phone: "(615) 555-1108",
    department: "maintenance",
    category: "property",
    jobTitle: "Maintenance Technician",
    propertyId: "prop-grandview",
    propertyName: "Grandview Apartments",
    payType: "hourly",
    payRate: 19,
  },
  {
    id: "hr-emp-gv-porter",
    employeeId: "HL-0109",
    firstName: "Amy",
    lastName: "Cruz",
    email: "amy.cruz@cpmc.demo",
    phone: "(615) 555-1109",
    department: "maintenance",
    category: "property",
    jobTitle: "Porter / Grounds",
    propertyId: "prop-grandview",
    propertyName: "Grandview Apartments",
    payType: "hourly",
    payRate: 17,
  },

  // —— Meridian Tower (Chicago office, 12 floors) ——
  {
    id: "hr-emp-mt-pm",
    employeeId: "HL-0201",
    firstName: "Helen",
    lastName: "Cho",
    email: "helen.cho@cpmc.demo",
    phone: "(312) 555-2101",
    department: "management",
    category: "property",
    jobTitle: "Property Manager",
    propertyId: "prop-meridian-tower",
    propertyName: "Meridian Tower",
    payType: "salary",
    payRate: 78000,
  },
  {
    id: "hr-emp-mt-chief",
    employeeId: "HL-0202",
    firstName: "Greg",
    lastName: "Malone",
    email: "greg.malone@cpmc.demo",
    phone: "(312) 555-2102",
    department: "maintenance",
    category: "property",
    jobTitle: "Chief Engineer",
    propertyId: "prop-meridian-tower",
    propertyName: "Meridian Tower",
    payType: "salary",
    payRate: 82000,
  },
  {
    id: "hr-emp-mt-eng",
    employeeId: "HL-0203",
    firstName: "Nate",
    lastName: "Kim",
    email: "nate.kim@cpmc.demo",
    phone: "(312) 555-2103",
    department: "maintenance",
    category: "property",
    jobTitle: "Building Engineer",
    propertyId: "prop-meridian-tower",
    propertyName: "Meridian Tower",
    payType: "salary",
    payRate: 58000,
  },
  {
    id: "hr-emp-mt-admin",
    employeeId: "HL-0204",
    firstName: "Rita",
    lastName: "Gomez",
    email: "rita.gomez@cpmc.demo",
    phone: "(312) 555-2104",
    department: "leasing",
    category: "property",
    jobTitle: "Office Administrator",
    propertyId: "prop-meridian-tower",
    propertyName: "Meridian Tower",
    payType: "salary",
    payRate: 46000,
  },
  {
    id: "hr-emp-mt-porter",
    employeeId: "HL-0205",
    firstName: "Paul",
    lastName: "Diaz",
    email: "paul.diaz@cpmc.demo",
    phone: "(312) 555-2105",
    department: "maintenance",
    category: "property",
    jobTitle: "Day Porter",
    propertyId: "prop-meridian-tower",
    propertyName: "Meridian Tower",
    payType: "hourly",
    payRate: 18.5,
  },

  // —— Riverbend Commerce Center (industrial / flex, Oxford MS) ——
  {
    id: "hr-emp-rb-pm",
    employeeId: "HL-0301",
    firstName: "Eli",
    lastName: "Foster",
    email: "eli.foster@cpmc.demo",
    phone: "(662) 555-3101",
    department: "management",
    category: "property",
    jobTitle: "Property Manager",
    propertyId: "00000000-0000-4000-8000-0000000000b1",
    propertyName: "Riverbend Commerce Center",
    payType: "salary",
    payRate: 62000,
  },
  {
    id: "hr-emp-rb-maint",
    employeeId: "HL-0302",
    firstName: "Hank",
    lastName: "Miller",
    email: "hank.miller@cpmc.demo",
    phone: "(662) 555-3102",
    department: "maintenance",
    category: "property",
    jobTitle: "Maintenance Technician",
    propertyId: "00000000-0000-4000-8000-0000000000b1",
    propertyName: "Riverbend Commerce Center",
    payType: "hourly",
    payRate: 23,
  },
  {
    id: "hr-emp-rb-admin",
    employeeId: "HL-0303",
    firstName: "Jade",
    lastName: "Simmons",
    email: "jade.simmons@cpmc.demo",
    phone: "(662) 555-3103",
    department: "leasing",
    category: "property",
    jobTitle: "Leasing & Admin Coordinator",
    propertyId: "00000000-0000-4000-8000-0000000000b1",
    propertyName: "Riverbend Commerce Center",
    payType: "salary",
    payRate: 42000,
  },
];

/** Fix duplicate key typo if any slipped in — validate at build time via map. */
export function buildHrEmployeeRecords(
  now = new Date().toISOString()
): HrEmployee[] {
  const seen = new Set<string>();
  const out: HrEmployee[] = [];
  for (const row of HARBORLINE_EMPLOYEE_ROSTER) {
    if (seen.has(row.id)) continue;
    seen.add(row.id);
    if (row.id === CADE_EMPLOYEE_ID) {
      const cade = makeCadeEmployee(now);
      out.push({
        ...cade,
        jobTitle: "Director of Operations",
        phone: row.phone || cade.phone,
        payRate: String(row.payRate),
        updatedAt: now,
      });
      continue;
    }
    out.push({
      id: row.id,
      employeeId: row.employeeId,
      firstName: row.firstName,
      lastName: row.lastName,
      email: row.email,
      phone: row.phone,
      department: row.department,
      category: row.category,
      jobTitle: row.jobTitle,
      status: "active",
      propertyId: row.propertyId,
      propertyName: row.propertyName,
      moduleAccess: resolveEmployeeModuleAccess(row.department, row.category),
      passwordHash: "",
      temporaryPassword: "",
      mustResetPassword: true,
      payType: row.payType,
      payRate: String(row.payRate),
      payFrequency: row.payFrequency || "biweekly",
      payEffectiveDate: TODAY,
      federalWithholding: "12% FIT (demo)",
      stateWithholding: "4% SIT (demo)",
      deductionsNotes: "FICA 7.65% EE + 3% benefits EE",
      directDepositBank: "CPMC Payroll ACH",
      directDepositAccountLast4: String(1000 + (out.length % 9000)).slice(-4),
      directDepositRoutingLast4: "0210",
      payrollNotes: `${row.category} · ${row.jobTitle}`,
      contractTitle: `${row.jobTitle} agreement`,
      contractStart: TODAY,
      contractEnd: "",
      contractFileName: "",
      contractNotes: "",
      hiredAt: TODAY,
      terminatedAt: "",
      notes: "",
      createdAt: now,
      updatedAt: now,
    });
  }
  return out;
}
