/**
 * Isolated Harborline mock fixtures for the Future Tenant Portal.
 *
 * BACKEND_TODO: replace with live inventory / CRM / leasing APIs.
 * Do not import this module from UI components for fetches — use services.
 */

import type {
  Applicant,
  AvailableUnit,
  FeePayment,
  FutureMessageThread,
  FutureNotification,
  LeaseOffer,
  MoveInTask,
  PropertySummary,
  RentalApplication,
  TourRequest,
} from "@/lib/portal/future/models";
import {
  FUTURE_DOCUMENTS,
  FUTURE_LEASE_OFFER,
  FUTURE_MESSAGES,
  FUTURE_ONBOARDING,
  FUTURE_STATUS,
  FUTURE_TOURS,
} from "@/lib/portal/future/paths";

export const DEMO_FUTURE_OWNER_USER_ID = "demo-future-applicant";

export const FUTURE_PROPERTIES: PropertySummary[] = [
  {
    id: "prop-pier12",
    name: "Pier 12 Residences",
    city: "Harbor City",
    neighborhood: "Waterfront",
    addressLine: "120 Harborline Pier, Harbor City, MS 39501",
    occupancyClass: "personal",
    propertyType: "multifamily",
  },
  {
    id: "prop-cove",
    name: "Harborline Cove",
    city: "Harbor City",
    neighborhood: "East Harbor",
    addressLine: "48 Cove Way, Harbor City, MS 39503",
    occupancyClass: "personal",
    propertyType: "multifamily",
  },
  {
    id: "prop-wharf",
    name: "Wharf House",
    city: "Bayview",
    neighborhood: "Wharf District",
    addressLine: "9 Wharf Lane, Bayview, MS 39507",
    occupancyClass: "personal",
    propertyType: "multifamily",
  },
  {
    id: "prop-pier12-commerce",
    name: "Pier 12 Commerce",
    city: "Harbor City",
    neighborhood: "Waterfront",
    addressLine: "120 Harborline Pier, Building A, Harbor City, MS 39501",
    occupancyClass: "commercial",
    propertyType: "office",
  },
  {
    id: "prop-canal",
    name: "Canal Yard",
    city: "Harbor City",
    neighborhood: "Industrial Canal",
    addressLine: "88 Canal Yard Rd, Harbor City, MS 39502",
    occupancyClass: "commercial",
    propertyType: "industrial",
  },
  {
    id: "prop-harborfront-retail",
    name: "Harborfront Retail Row",
    city: "Harbor City",
    neighborhood: "Boardwalk",
    addressLine: "15 Boardwalk Ave, Harbor City, MS 39501",
    occupancyClass: "commercial",
    propertyType: "retail",
  },
];

const FEES_DISCLAIMER =
  "Quoted rent and fees may change until a lease is fully executed. Application fees are typically non-refundable. Confirm current pricing with Harborline Leasing.";

const COMMON_REQUIREMENTS = [
  "Government-issued photo identification",
  "Proof of income (recent pay stubs or offer letter)",
  "Completed rental application for each adult applicant",
  "Application fee per adult applicant",
];

type UnitSeed = Omit<AvailableUnit, "occupancyClass" | "propertyType">;

const PERSONAL_UNIT_SEEDS: UnitSeed[] = [
  {
    id: "unit-p12-304",
    propertyId: "prop-pier12",
    propertyName: "Pier 12 Residences",
    unitLabel: "Unit 304",
    floorPlan: "Harbor One-Bedroom",
    rent: 1850,
    deposit: 1850,
    beds: 1,
    baths: 1,
    sqft: 742,
    availableDate: "2026-09-01",
    imageUrl: "/placeholders/unit-1.jpg",
    galleryUrls: [
      "/placeholders/unit-1.jpg",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    ],
    amenities: ["In-unit washer/dryer", "Balcony", "Smart thermostat", "Fitness center"],
    petFriendly: true,
    accessibility: ["Elevator access", "Lever door handles"],
    availability: "available",
    location: { city: "Harbor City", neighborhood: "Waterfront" },
    description:
      "Bright one-bedroom overlooking the pier boardwalk with open living space and a private balcony.",
    utilities: "Water and trash included. Resident pays electric and internet.",
    parking: "One reserved garage space included. Additional spaces $95/month when available.",
    petPolicy: "Cats and dogs welcome (breed restrictions apply). Pet rent $35/month + $300 deposit.",
    leaseTermOptions: ["12 months", "14 months", "18 months"],
    applicationRequirements: COMMON_REQUIREMENTS,
    feesDisclaimer: FEES_DISCLAIMER,
    listedAt: "2026-07-20T14:00:00.000Z",
  },
  {
    id: "unit-p12-512",
    propertyId: "prop-pier12",
    propertyName: "Pier 12 Residences",
    unitLabel: "Unit 512",
    floorPlan: "Pier Two-Bedroom",
    rent: 2450,
    deposit: 2450,
    beds: 2,
    baths: 2,
    sqft: 1088,
    availableDate: "2026-08-15",
    imageUrl: "/placeholders/unit-2.jpg",
    galleryUrls: [
      "/placeholders/unit-2.jpg",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    ],
    amenities: [
      "In-unit washer/dryer",
      "Harbor view",
      "Walk-in closet",
      "Package lockers",
      "Rooftop lounge",
    ],
    petFriendly: true,
    accessibility: ["Elevator access", "Wide doorways", "Roll-in shower (select baths)"],
    availability: "limited",
    location: { city: "Harbor City", neighborhood: "Waterfront" },
    description:
      "Corner two-bedroom with dual baths and floor-to-ceiling windows facing the harbor channel.",
    utilities: "Water, trash, and basic cable included. Resident pays electric.",
    parking: "Two tandem garage spaces available (+$150/month).",
    petPolicy: "Up to two pets. Pet interview required. Pet rent $40/month each.",
    leaseTermOptions: ["12 months", "15 months"],
    applicationRequirements: [
      ...COMMON_REQUIREMENTS,
      "Rental history for the last 24 months",
    ],
    feesDisclaimer: FEES_DISCLAIMER,
    listedAt: "2026-07-28T10:30:00.000Z",
  },
  {
    id: "unit-p12-118",
    propertyId: "prop-pier12",
    propertyName: "Pier 12 Residences",
    unitLabel: "Unit 118",
    floorPlan: "Studio Drift",
    rent: 1425,
    deposit: 1425,
    beds: 0,
    baths: 1,
    sqft: 518,
    availableDate: "2026-10-01",
    imageUrl: "/placeholders/unit-3.jpg",
    amenities: ["Efficient layout", "Bike storage", "Shared courtyard"],
    petFriendly: false,
    accessibility: ["Ground-level entry", "Elevator access"],
    availability: "coming_soon",
    location: { city: "Harbor City", neighborhood: "Waterfront" },
    description:
      "Compact studio ideal for professionals who want pier living with low commute friction.",
    utilities: "Water and trash included. Resident pays electric and internet.",
    parking: "Surface lot waitlist. Transit and bike storage encouraged.",
    petPolicy: "No pets in studio inventory at this time.",
    leaseTermOptions: ["12 months"],
    applicationRequirements: COMMON_REQUIREMENTS,
    feesDisclaimer: FEES_DISCLAIMER,
    listedAt: "2026-08-01T16:00:00.000Z",
  },
  {
    id: "unit-cove-210",
    propertyId: "prop-cove",
    propertyName: "Harborline Cove",
    unitLabel: "Unit 210",
    floorPlan: "Cove One-Bedroom+",
    rent: 1695,
    deposit: 1695,
    beds: 1,
    baths: 1,
    sqft: 810,
    availableDate: "2026-08-20",
    imageUrl: "/placeholders/unit-4.jpg",
    galleryUrls: [
      "/placeholders/unit-4.jpg",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
    ],
    amenities: ["Den / flex space", "Quartz counters", "Community garden", "EV charging"],
    petFriendly: true,
    accessibility: ["Elevator access", "Accessible parking nearby"],
    availability: "available",
    location: { city: "Harbor City", neighborhood: "East Harbor" },
    description:
      "One-bedroom plus den with soft cove light, updated kitchen, and quick access to East Harbor trails.",
    utilities: "Water and trash included. Resident pays electric, gas, and internet.",
    parking: "One covered space included.",
    petPolicy: "Pets welcome under 50 lb. Pet rent $30/month.",
    leaseTermOptions: ["12 months", "13 months", "24 months"],
    applicationRequirements: COMMON_REQUIREMENTS,
    feesDisclaimer: FEES_DISCLAIMER,
    listedAt: "2026-07-12T09:00:00.000Z",
  },
  {
    id: "unit-cove-405",
    propertyId: "prop-cove",
    propertyName: "Harborline Cove",
    unitLabel: "Unit 405",
    floorPlan: "Cove Two-Bedroom",
    rent: 2195,
    deposit: 2200,
    beds: 2,
    baths: 2,
    sqft: 1012,
    availableDate: "2026-09-15",
    imageUrl: "/placeholders/unit-5.jpg",
    amenities: [
      "Dual vanities",
      "In-unit washer/dryer",
      "Coworking lounge",
      "Pet spa",
    ],
    petFriendly: true,
    accessibility: ["Elevator access", "Visual fire alarms available on request"],
    availability: "available",
    location: { city: "Harbor City", neighborhood: "East Harbor" },
    description:
      "Family-ready two-bedroom with split bedrooms, dedicated work nook, and community amenities.",
    utilities: "Water, trash, and pest control included.",
    parking: "One assigned space; second space $85/month.",
    petPolicy: "Two pets max. Vaccination records required at move-in.",
    leaseTermOptions: ["12 months", "18 months"],
    applicationRequirements: [
      ...COMMON_REQUIREMENTS,
      "Pet vaccination records (if applicable)",
    ],
    feesDisclaimer: FEES_DISCLAIMER,
    listedAt: "2026-07-25T11:15:00.000Z",
  },
  {
    id: "unit-cove-102",
    propertyId: "prop-cove",
    propertyName: "Harborline Cove",
    unitLabel: "Unit 102",
    floorPlan: "Garden Flat",
    rent: 1575,
    deposit: 1575,
    beds: 1,
    baths: 1,
    sqft: 690,
    availableDate: "2026-08-10",
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    amenities: ["Private patio", "Garden access", "Storage cage"],
    petFriendly: true,
    accessibility: ["Step-free entry", "Roll-under sink"],
    availability: "limited",
    location: { city: "Harbor City", neighborhood: "East Harbor" },
    description:
      "Garden-level one-bedroom with a private patio—quiet mornings and easy grocery runs nearby.",
    utilities: "Water and trash included.",
    parking: "Surface lot space included.",
    petPolicy: "Pets welcome. Yard access via shared garden paths.",
    leaseTermOptions: ["12 months"],
    applicationRequirements: COMMON_REQUIREMENTS,
    feesDisclaimer: FEES_DISCLAIMER,
    listedAt: "2026-06-30T13:45:00.000Z",
  },
  {
    id: "unit-wharf-6b",
    propertyId: "prop-wharf",
    propertyName: "Wharf House",
    unitLabel: "Unit 6B",
    floorPlan: "Wharf Loft",
    rent: 2750,
    deposit: 2750,
    beds: 2,
    baths: 2,
    sqft: 1240,
    availableDate: "2026-11-01",
    imageUrl: "/placeholders/unit-6.jpg",
    galleryUrls: [
      "/placeholders/unit-6.jpg",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
    ],
    amenities: [
      "Double-height living",
      "Chef kitchen",
      "Secure entry",
      "Concierge desk",
    ],
    petFriendly: false,
    accessibility: ["Elevator access", "Braille elevator controls"],
    availability: "coming_soon",
    location: { city: "Bayview", neighborhood: "Wharf District" },
    description:
      "Industrial loft with mezzanine sleeping area, polished concrete floors, and district restaurant access.",
    utilities: "Trash included. Resident pays electric, water, and internet.",
    parking: "One underground space included; valet available evenings.",
    petPolicy: "No pets in loft inventory.",
    leaseTermOptions: ["12 months", "24 months"],
    applicationRequirements: [
      ...COMMON_REQUIREMENTS,
      "Employment verification letter",
    ],
    feesDisclaimer: FEES_DISCLAIMER,
    listedAt: "2026-08-03T08:00:00.000Z",
  },
  {
    id: "unit-wharf-3a",
    propertyId: "prop-wharf",
    propertyName: "Wharf House",
    unitLabel: "Unit 3A",
    floorPlan: "Wharf One-Bedroom",
    rent: 1995,
    deposit: 1995,
    beds: 1,
    baths: 1,
    sqft: 860,
    availableDate: "2026-09-05",
    imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80",
    amenities: ["Exposed brick", "High ceilings", "Bike room", "Shared roof deck"],
    petFriendly: true,
    accessibility: ["Elevator access"],
    availability: "available",
    location: { city: "Bayview", neighborhood: "Wharf District" },
    description:
      "Character-filled one-bedroom steps from the ferry landing with soft evening deck views.",
    utilities: "Water and trash included.",
    parking: "Neighborhood permit parking; limited on-site stalls waitlisted.",
    petPolicy: "Cats and small dogs welcome. Pet rent $35/month.",
    leaseTermOptions: ["12 months", "15 months"],
    applicationRequirements: COMMON_REQUIREMENTS,
    feesDisclaimer: FEES_DISCLAIMER,
    listedAt: "2026-07-18T17:20:00.000Z",
  },
];

const COMMERCIAL_REQUIREMENTS = [
  "Business formation documents or doing-business-as certificate",
  "Government-issued photo identification for authorized signers",
  "Proof of business income or bank statements",
  "Completed commercial rental application",
  "Application fee per applying entity",
];

const COMMERCIAL_UNIT_SEEDS: AvailableUnit[] = [
  {
    id: "unit-p12c-118",
    propertyId: "prop-pier12-commerce",
    propertyName: "Pier 12 Commerce",
    unitLabel: "Suite 118",
    floorPlan: "Lobby Retail",
    occupancyClass: "commercial",
    propertyType: "retail",
    rent: 3200,
    deposit: 6400,
    beds: 0,
    baths: 1,
    sqft: 980,
    availableDate: "2026-09-01",
    imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
    amenities: ["Street frontage", "Glass storefront", "Shared loading dock", "Building security"],
    petFriendly: false,
    accessibility: ["Step-free entry", "Wide doorways"],
    availability: "available",
    location: { city: "Harbor City", neighborhood: "Waterfront" },
    description:
      "Ground-floor retail suite with pier boardwalk frontage, ideal for boutique or cafe concepts.",
    utilities: "Landlord provides common-area heating and cooling. Tenant pays suite electric and internet.",
    parking: "Two reserved garage spaces included. Customer validated parking available.",
    petPolicy: "Service animals only under ADA. No pets for commercial suites.",
    leaseTermOptions: ["36 months", "60 months"],
    applicationRequirements: COMMERCIAL_REQUIREMENTS,
    feesDisclaimer: FEES_DISCLAIMER,
    listedAt: "2026-07-28T11:00:00.000Z",
  },
  {
    id: "unit-p12c-400",
    propertyId: "prop-pier12-commerce",
    propertyName: "Pier 12 Commerce",
    unitLabel: "Suite 400",
    floorPlan: "Harbor Office",
    occupancyClass: "commercial",
    propertyType: "office",
    rent: 5400,
    deposit: 5400,
    beds: 0,
    baths: 2,
    sqft: 2100,
    availableDate: "2026-08-15",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
    amenities: ["Conference room", "Fiber internet riser", "Harbor view", "After-hours heating and cooling"],
    petFriendly: false,
    accessibility: ["Elevator access", "Accessible restrooms"],
    availability: "available",
    location: { city: "Harbor City", neighborhood: "Waterfront" },
    description:
      "Full-floor corner office with open collaboration area, private offices, and pier views.",
    utilities: "Base building services included. Tenant pays suite electric above allowance.",
    parking: "Four reserved garage spaces included.",
    petPolicy: "Service animals only.",
    leaseTermOptions: ["36 months", "60 months", "84 months"],
    applicationRequirements: COMMERCIAL_REQUIREMENTS,
    feesDisclaimer: FEES_DISCLAIMER,
    listedAt: "2026-08-01T09:30:00.000Z",
  },
  {
    id: "unit-canal-b2",
    propertyId: "prop-canal",
    propertyName: "Canal Yard",
    unitLabel: "Bay B2",
    floorPlan: "Flex Warehouse",
    occupancyClass: "commercial",
    propertyType: "industrial",
    rent: 4100,
    deposit: 8200,
    beds: 0,
    baths: 1,
    sqft: 4500,
    availableDate: "2026-10-01",
    imageUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80",
    amenities: ["Grade-level loading", "Clear height 18 ft", "Fenced yard", "Office build-out"],
    petFriendly: false,
    accessibility: ["Grade-level entry"],
    availability: "limited",
    location: { city: "Harbor City", neighborhood: "Industrial Canal" },
    description:
      "Flexible warehouse bay with small office frontage and shared yard access for light industrial use.",
    utilities: "Tenant pays all utilities metered to the bay.",
    parking: "Six surface stalls assigned to Bay B2.",
    petPolicy: "Not applicable — industrial occupancy.",
    leaseTermOptions: ["24 months", "36 months", "60 months"],
    applicationRequirements: COMMERCIAL_REQUIREMENTS,
    feesDisclaimer: FEES_DISCLAIMER,
    listedAt: "2026-07-12T16:00:00.000Z",
  },
  {
    id: "unit-retail-7",
    propertyId: "prop-harborfront-retail",
    propertyName: "Harborfront Retail Row",
    unitLabel: "Shop 7",
    floorPlan: "Boardwalk Shopfront",
    occupancyClass: "commercial",
    propertyType: "retail",
    rent: 2750,
    deposit: 5500,
    beds: 0,
    baths: 1,
    sqft: 720,
    availableDate: "2026-08-20",
    imageUrl: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&q=80",
    amenities: ["Boardwalk frontage", "Display windows", "Shared restrooms", "Signage band"],
    petFriendly: false,
    accessibility: ["Step-free entry", "Wide doorways"],
    availability: "available",
    location: { city: "Harbor City", neighborhood: "Boardwalk" },
    description:
      "Compact retail shopfront on the boardwalk corridor with strong weekend foot traffic.",
    utilities: "Water and trash included. Tenant pays electric and internet.",
    parking: "Shared customer lot behind the row; one staff stall included.",
    petPolicy: "Service animals only.",
    leaseTermOptions: ["24 months", "36 months"],
    applicationRequirements: COMMERCIAL_REQUIREMENTS,
    feesDisclaimer: FEES_DISCLAIMER,
    listedAt: "2026-08-04T13:15:00.000Z",
  },
];

export const AVAILABLE_UNITS: AvailableUnit[] = [
  ...PERSONAL_UNIT_SEEDS.map((unit) => ({
    ...unit,
    occupancyClass: "personal" as const,
    propertyType: "multifamily" as const,
  })),
  ...COMMERCIAL_UNIT_SEEDS,
];

export function getMockApplicant(ownerUserId: string): Applicant {
  return {
    id: `applicant-${ownerUserId}`,
    ownerUserId,
    firstName: "Riley",
    lastName: "Applicant",
    preferredName: "Riley",
    email: "riley.applicant@example.com",
    phone: "555-555-0188",
    preferredContactMethod: "email",
    currentAddress: {
      line1: "220 Market Street",
      line2: "Apt 4",
      city: "Harbor City",
      state: "MS",
      postalCode: "39501",
    },
    desiredMoveInDate: "2026-09-01",
    preferredPropertyId: "prop-pier12",
    preferredUnitType: "1 bedroom",
    createdAt: "2026-07-01T12:00:00.000Z",
    updatedAt: "2026-08-01T12:00:00.000Z",
  };
}

function buildDemoFee(applicationId: string, ownerUserId: string): FeePayment {
  return {
    id: `fee-${applicationId}`,
    applicationId,
    ownerUserId,
    amountCents: 7500,
    currency: "USD",
    status: "paid",
    receiptNumber: "HL-FEE-2026-1042",
    paidAt: "2026-07-22T15:40:00.000Z",
    refundable: false,
    explanation:
      "Non-refundable application fee covering screening and administrative review for each adult applicant.",
  };
}

/** Seeded demo application in Under Review for the demo owner. */
export function getSeedDemoApplication(
  ownerUserId: string = DEMO_FUTURE_OWNER_USER_ID
): RentalApplication {
  const applicationId = `app-${ownerUserId}-demo`;
  return {
    id: applicationId,
    applicationNumber: "HL-APP-2026-8841",
    ownerUserId,
    applicantName: "Riley Applicant",
    propertyId: "prop-pier12",
    propertyName: "Pier 12 Residences",
    unitId: "unit-p12-304",
    unitLabel: "Unit 304",
    status: "Under Review",
    currentStep: "16",
    submittedAt: "2026-07-22T16:05:00.000Z",
    lastUpdatedAt: "2026-08-02T09:30:00.000Z",
    nextRequiredAction:
      "Harborline is reviewing your application. No action needed unless leasing contacts you.",
    confirmationNumber: "CONF-HL-8841",
    coApplicants: [
      {
        id: "co-primary",
        applicationId,
        role: "primary",
        firstName: "Riley",
        lastName: "Applicant",
        email: "riley.applicant@example.com",
        phone: "555-555-0188",
        relationship: "Self",
        inviteStatus: "accepted",
      },
      {
        id: "co-jordan",
        applicationId,
        role: "co_applicant",
        firstName: "Jordan",
        lastName: "Lee",
        email: "jordan.lee@example.com",
        phone: "555-555-0190",
        relationship: "Partner",
        inviteStatus: "accepted",
      },
      {
        id: "occ-sam",
        applicationId,
        role: "adult_occupant",
        firstName: "Sam",
        lastName: "Lee",
        email: null,
        phone: null,
        relationship: "Sibling",
        inviteStatus: "not_sent",
      },
    ],
    documents: [
      {
        id: "doc-income",
        applicationId,
        ownerUserId,
        category: "proof_of_income",
        fileName: "paystubs-july.pdf",
        fileType: "application/pdf",
        fileSizeBytes: 240_112,
        status: "accepted",
        uploadedAt: "2026-07-21T18:00:00.000Z",
        previewUrl: null,
      },
      {
        id: "doc-id",
        applicationId,
        ownerUserId,
        category: "government_id",
        fileName: "id-preview.pdf",
        fileType: "application/pdf",
        fileSizeBytes: 180_440,
        status: "under_review",
        uploadedAt: "2026-07-21T18:05:00.000Z",
        previewUrl: null,
      },
    ],
    feePayment: buildDemoFee(applicationId, ownerUserId),
    draftPayload: {
      employment: { employer: "Harbor Tech", monthlyIncome: 6200 },
      pets: { hasPets: false },
    },
    certifiedAt: "2026-07-22T16:00:00.000Z",
  };
}

export function getMockTourRequests(ownerUserId: string): TourRequest[] {
  return [
    {
      id: `tour-${ownerUserId}-1`,
      ownerUserId,
      propertyId: "prop-pier12",
      propertyName: "Pier 12 Residences",
      unitId: "unit-p12-304",
      unitLabel: "Unit 304",
      tourType: "in_person",
      date: "2026-08-12",
      timeSlot: "10:00",
      guestCount: 2,
      contactName: "Riley Applicant",
      contactEmail: "riley.applicant@example.com",
      contactPhone: "555-555-0188",
      accessibilityRequests: "",
      notes: "Interested in balcony units.",
      status: "scheduled",
      createdAt: "2026-08-01T14:00:00.000Z",
      updatedAt: "2026-08-01T14:00:00.000Z",
    },
  ];
}

export function getMockMessageThreads(
  ownerUserId: string
): FutureMessageThread[] {
  return [
    {
      id: `thread-${ownerUserId}-leasing`,
      ownerUserId,
      subject: "Question about Pier 12 Unit 304",
      topic: "unit_question",
      lastMessageAt: "2026-08-03T11:20:00.000Z",
      preview: "Thanks — we can hold a tour slot for Thursday morning.",
      unreadCount: 1,
      messages: [
        {
          id: `msg-${ownerUserId}-1`,
          threadId: `thread-${ownerUserId}-leasing`,
          senderRole: "applicant",
          senderName: "Riley Applicant",
          body: "Is Unit 304 still available for a September 1 move-in?",
          sentAt: "2026-08-02T16:10:00.000Z",
          attachments: [],
          deliveryStatus: "sent",
        },
        {
          id: `msg-${ownerUserId}-2`,
          threadId: `thread-${ownerUserId}-leasing`,
          senderRole: "leasing",
          senderName: "Harborline Leasing",
          body: "Thanks — we can hold a tour slot for Thursday morning.",
          sentAt: "2026-08-03T11:20:00.000Z",
          attachments: [],
          deliveryStatus: "sent",
        },
      ],
    },
    {
      id: `thread-${ownerUserId}-docs`,
      ownerUserId,
      subject: "Application documents",
      topic: "missing_documents",
      lastMessageAt: "2026-07-28T09:00:00.000Z",
      preview: "Your pay stubs were accepted. Identification is still under review.",
      unreadCount: 0,
      messages: [
        {
          id: `msg-${ownerUserId}-3`,
          threadId: `thread-${ownerUserId}-docs`,
          senderRole: "leasing",
          senderName: "Harborline Leasing",
          body: "Your pay stubs were accepted. Identification is still under review.",
          sentAt: "2026-07-28T09:00:00.000Z",
          attachments: [],
          deliveryStatus: "sent",
        },
      ],
    },
  ];
}

export function getMockLeaseOffer(ownerUserId: string): LeaseOffer | null {
  // Demo applicant is Under Review — no offer yet by default.
  if (ownerUserId === DEMO_FUTURE_OWNER_USER_ID) return null;
  return null;
}

export function getMockApprovedLeaseOffer(ownerUserId: string): LeaseOffer {
  return {
    id: `offer-${ownerUserId}`,
    ownerUserId,
    applicationId: `app-${ownerUserId}-demo`,
    propertyId: "prop-pier12",
    propertyName: "Pier 12 Residences",
    unitId: "unit-p12-304",
    unitLabel: "Unit 304",
    occupancyClass: "personal",
    propertyType: "multifamily",
    rent: 1850,
    deposit: 1850,
    leaseStartDate: "2026-09-01",
    leaseEndDate: "2027-08-31",
    leaseTerm: "12 months",
    includedUtilities: "Water and trash",
    fees: ["Application fee (paid)", "Admin fee $150 due at lease signing"],
    parking: "One reserved garage space included",
    petTerms: "One pet permitted with pet rent and deposit as listed in offer packet",
    offerExpiresAt: "2026-08-20T23:59:59.000Z",
    requiredNextSteps: [
      "Review lease documents",
      "Accept offer in the portal",
      "Complete electronic signatures when prompted",
      "Pay deposit and first month per instructions",
    ],
    status: "available",
    documentTitles: [
      "Residential Lease — Pier 12 Unit 304",
      "Community Rules Addendum",
      "Pet Addendum",
    ],
    acceptedAt: null,
    declinedAt: null,
  };
}

export function getMockMoveInTasks(ownerUserId: string): MoveInTask[] {
  return [
    {
      id: "sign_lease",
      ownerUserId,
      label: "Sign Lease",
      description: "Complete electronic lease signatures when Harborline issues them.",
      complete: false,
      required: true,
      deadline: "2026-08-25",
      requiredDocuments: ["Signed lease packet"],
      href: FUTURE_LEASE_OFFER,
    },
    {
      id: "pay_deposit",
      ownerUserId,
      label: "Pay Deposit",
      description: "Pay the security deposit through the approved Harborline method.",
      complete: false,
      required: true,
      deadline: "2026-08-28",
      requiredDocuments: ["Deposit receipt"],
      href: FUTURE_ONBOARDING,
    },
    {
      id: "pay_first_month",
      ownerUserId,
      label: "Pay First Month’s Rent",
      description: "Submit first month’s rent before key pickup.",
      complete: false,
      required: true,
      deadline: "2026-08-28",
      requiredDocuments: [],
      href: FUTURE_ONBOARDING,
    },
    {
      id: "renters_insurance",
      ownerUserId,
      label: "Provide Renter’s Insurance",
      description: "Upload a declarations page naming Harborline as interested party.",
      complete: false,
      required: true,
      deadline: "2026-08-30",
      requiredDocuments: ["Insurance declarations page"],
      href: FUTURE_DOCUMENTS,
    },
    {
      id: "set_up_utilities",
      ownerUserId,
      label: "Set Up Utilities",
      description: "Transfer electric and internet into your name effective move-in day.",
      complete: false,
      required: true,
      deadline: "2026-08-30",
      requiredDocuments: [],
      href: null,
    },
    {
      id: "confirm_occupants",
      ownerUserId,
      label: "Confirm Occupants",
      description: "Confirm all adults and minors who will occupy the unit.",
      complete: true,
      required: true,
      deadline: "2026-08-20",
      requiredDocuments: [],
      href: FUTURE_STATUS,
    },
    {
      id: "register_vehicles",
      ownerUserId,
      label: "Register Vehicles",
      description: "Register vehicles for parking permits.",
      complete: false,
      required: false,
      deadline: null,
      requiredDocuments: ["Vehicle registration"],
      href: FUTURE_ONBOARDING,
    },
    {
      id: "register_pets",
      ownerUserId,
      label: "Register Pets",
      description: "Register pets and provide vaccination records if applicable.",
      complete: false,
      required: false,
      deadline: null,
      requiredDocuments: ["Pet vaccination records"],
      href: FUTURE_ONBOARDING,
    },
    {
      id: "schedule_key_pickup",
      ownerUserId,
      label: "Schedule Key Pickup",
      description: "Book a key pickup window with the leasing office.",
      complete: false,
      required: true,
      deadline: "2026-08-31",
      requiredDocuments: [],
      href: FUTURE_TOURS,
    },
    {
      id: "review_instructions",
      ownerUserId,
      label: "Review Instructions",
      description: "Read move-in instructions and community guidelines.",
      complete: false,
      required: true,
      deadline: "2026-08-31",
      requiredDocuments: [],
      href: FUTURE_ONBOARDING,
    },
    {
      id: "move_in_inspection",
      ownerUserId,
      label: "Complete Move-In Inspection",
      description: "Complete the move-in inspection checklist on arrival.",
      complete: false,
      required: true,
      deadline: "2026-09-01",
      requiredDocuments: ["Move-in inspection form"],
      href: FUTURE_ONBOARDING,
    },
  ];
}

export function getMockFutureNotifications(
  ownerUserId: string
): FutureNotification[] {
  return [
    {
      id: `fn-${ownerUserId}-tour`,
      ownerUserId,
      type: "tour_confirmed",
      category: "Tours",
      title: "Tour confirmed",
      body: "Your in-person tour at Pier 12 Residences on Aug 12 at 10:00 AM is confirmed.",
      createdAt: "2026-08-01T14:05:00.000Z",
      href: FUTURE_TOURS,
      hrefLabel: "View tours",
      read: false,
    },
    {
      id: `fn-${ownerUserId}-submitted`,
      ownerUserId,
      type: "application_submitted",
      category: "Application",
      title: "Application submitted",
      body: "Harborline received application HL-APP-2026-8841 for Pier 12 Unit 304.",
      createdAt: "2026-07-22T16:06:00.000Z",
      href: FUTURE_STATUS,
      hrefLabel: "View status",
      read: true,
    },
    {
      id: `fn-${ownerUserId}-status`,
      ownerUserId,
      type: "application_status_updated",
      category: "Application",
      title: "Application status updated",
      body: "Your application is now Under Review.",
      createdAt: "2026-08-02T09:30:00.000Z",
      href: FUTURE_STATUS,
      hrefLabel: "View status",
      read: false,
    },
    {
      id: `fn-${ownerUserId}-docs`,
      ownerUserId,
      type: "document_requested",
      category: "Documents",
      title: "Document requested",
      body: "Leasing may request a clearer identification scan if the current upload is unreadable.",
      createdAt: "2026-07-28T09:05:00.000Z",
      href: FUTURE_DOCUMENTS,
      hrefLabel: "Upload documents",
      read: true,
    },
    {
      id: `fn-${ownerUserId}-msg`,
      ownerUserId,
      type: "new_message",
      category: "Messages",
      title: "New message",
      body: "Harborline Leasing replied about Pier 12 Unit 304.",
      createdAt: "2026-08-03T11:21:00.000Z",
      href: FUTURE_MESSAGES,
      hrefLabel: "Open messages",
      read: false,
    },
    {
      id: `fn-${ownerUserId}-offer-deadline`,
      ownerUserId,
      type: "offer_deadline_approaching",
      category: "Lease Offer",
      title: "Offer deadline approaching",
      body: "If you receive a lease offer, respond before the posted expiration date.",
      createdAt: "2026-08-04T08:00:00.000Z",
      href: FUTURE_LEASE_OFFER,
      hrefLabel: "Review lease offer",
      read: true,
    },
    {
      id: `fn-${ownerUserId}-task`,
      ownerUserId,
      type: "move_in_task_due",
      category: "Move-In",
      title: "Move-in task due",
      body: "After approval, confirm occupants and prepare insurance documents.",
      createdAt: "2026-08-05T10:00:00.000Z",
      href: FUTURE_ONBOARDING,
      hrefLabel: "View onboarding",
      read: false,
    },
  ];
}

export function findUnitById(id: string): AvailableUnit | undefined {
  return AVAILABLE_UNITS.find((unit) => unit.id === id);
}

export function listPropertyOptions(): PropertySummary[] {
  return FUTURE_PROPERTIES;
}
