import type { MaintenanceRequest } from "@/lib/portal/maintenance-types";

/** Isolated mock maintenance requests for the current-tenant portal. */
export function getMockMaintenanceRequests(): MaintenanceRequest[] {
  return [
    {
      id: "maint-1",
      requestNumber: "MR-2026-0142",
      category: "Heating or Cooling",
      priority: "High",
      title: "Heating and cooling not working in suite",
      submittedOn: "2026-04-22",
      status: "Open",
      scheduledOn: null,
      technicianName: null,
      lastUpdate: "2026-04-28",
      location: "Pier 12 · Suite 210",
    },
    {
      id: "maint-2",
      requestNumber: "MR-2026-0138",
      category: "Lock or Security",
      priority: "Normal",
      title: "Lobby badge reader intermittent",
      submittedOn: "2026-04-20",
      status: "Scheduled",
      scheduledOn: "2026-05-02",
      technicianName: "Jordan Lee",
      lastUpdate: "2026-04-26",
      location: "Pier 12 · Main lobby",
    },
    {
      id: "maint-3",
      requestNumber: "MR-2026-0121",
      category: "Plumbing",
      priority: "Emergency",
      title: "Restroom sink leaking under vanity",
      submittedOn: "2026-04-10",
      status: "Scheduled",
      scheduledOn: "2026-04-30",
      technicianName: "Sam Ortiz",
      lastUpdate: "2026-04-29",
      location: "Pier 12 · Suite 210 restroom",
    },
    {
      id: "maint-4",
      requestNumber: "MR-2026-0099",
      category: "Electrical",
      priority: "Normal",
      title: "Flickering lights in conference nook",
      submittedOn: "2026-03-18",
      status: "Completed",
      scheduledOn: "2026-03-22",
      technicianName: "Alex Kim",
      lastUpdate: "2026-03-22",
      location: "Pier 12 · Suite 210",
    },
    {
      id: "maint-5",
      requestNumber: "MR-2026-0084",
      category: "Appliance",
      priority: "Low",
      title: "Breakroom fridge ice maker slow",
      submittedOn: "2026-03-02",
      status: "Completed",
      scheduledOn: "2026-03-08",
      technicianName: "Jordan Lee",
      lastUpdate: "2026-03-09",
      location: "Pier 12 · Floor 2 breakroom",
    },
    {
      id: "maint-6",
      requestNumber: "MR-2026-0071",
      category: "Common Area",
      priority: "Low",
      title: "Touch-up paint on corridor scuff",
      submittedOn: "2026-02-14",
      status: "Cancelled",
      scheduledOn: null,
      technicianName: null,
      lastUpdate: "2026-02-20",
      location: "Pier 12 · Corridor B",
    },
    {
      id: "maint-7",
      requestNumber: "MR-2026-0060",
      category: "Other",
      priority: "Normal",
      title: "Window blind cord tangled",
      submittedOn: "2026-02-01",
      status: "Open",
      scheduledOn: null,
      technicianName: null,
      lastUpdate: "2026-02-03",
      location: "Pier 12 · Suite 210 south window",
    },
    {
      id: "maint-8",
      requestNumber: "MR-2025-0199",
      category: "Plumbing",
      priority: "High",
      title: "Slow drain in utility closet",
      submittedOn: "2025-12-12",
      status: "Completed",
      scheduledOn: "2025-12-15",
      technicianName: "Sam Ortiz",
      lastUpdate: "2025-12-16",
      location: "Pier 12 · Suite 210",
    },
  ];
}

export const MAINTENANCE_PROPERTY_OPTIONS = [
  "Pier 12 · Suite 210",
  "Pier 12 · Suite 305",
  "Canal Yard · Unit B",
  "Harbor Court · Floor 3",
] as const;
