import type { PortalNotification } from "@/lib/portal/notifications-types";

/** Isolated in-portal notifications for the current-tenant portal (no external delivery). */
export function getMockPortalNotifications(): PortalNotification[] {
  return [
    {
      id: "notif-1",
      type: "rent_due",
      category: "Payments",
      title: "May rent is due",
      body: "Your May rent of $4,800.00 is due May 1. You can pay in the portal.",
      createdAt: "2026-04-28T09:00:00",
      href: "/portal/payments/make",
      hrefLabel: "Make a payment",
    },
    {
      id: "notif-2",
      type: "payment_received",
      category: "Payments",
      title: "April payment received",
      body: "Harborline recorded your April rent payment of $4,800.00.",
      createdAt: "2026-04-01T16:20:00",
      href: "/portal/payments/history",
      hrefLabel: "View payment history",
    },
    {
      id: "notif-3",
      type: "payment_failed",
      category: "Payments",
      title: "Payment attempt failed",
      body: "A recent payment attempt did not complete. Review your method and try again.",
      createdAt: "2026-03-15T11:05:00",
      href: "/portal/payments",
      hrefLabel: "Open payments",
    },
    {
      id: "notif-4",
      type: "maintenance_updated",
      category: "Maintenance",
      title: "Maintenance request updated",
      body: "HVAC not cooling in suite (MR-2026-0142) has a new status update.",
      createdAt: "2026-04-28T16:20:00",
      href: "/portal/maintenance/maint-1",
      hrefLabel: "View request",
    },
    {
      id: "notif-5",
      type: "new_announcement",
      category: "Announcements",
      title: "New announcement posted",
      body: "Scheduled fire drill — May 8 has been posted for Pier 12.",
      createdAt: "2026-04-20T10:14:00",
      href: "/portal/announcements",
      hrefLabel: "View announcements",
    },
    {
      id: "notif-6",
      type: "new_message",
      category: "Messages",
      title: "New message from Harborline",
      body: "Harborline Billing replied in “April rent confirmation.”",
      createdAt: "2026-04-28T15:42:00",
      href: "/portal/messages",
      hrefLabel: "Open messages",
    },
    {
      id: "notif-7",
      type: "lease_renewal_deadline",
      category: "Lease",
      title: "Renewal deadline reminder",
      body: "Your lease renewal deadline is Sep 30, 2027. You can submit a renewal request in the portal.",
      createdAt: "2026-04-15T08:30:00",
      href: "/portal/renewal",
      hrefLabel: "Request renewal",
    },
    {
      id: "notif-8",
      type: "new_document",
      category: "Documents",
      title: "New document available",
      body: "A new file was shared with you: pier12-suite-210-lease-2026.pdf.",
      createdAt: "2026-01-02T12:00:00",
      href: "/portal/documents",
      hrefLabel: "Open documents",
    },
    {
      id: "notif-9",
      type: "maintenance_updated",
      category: "Maintenance",
      title: "Maintenance visit scheduled",
      body: "Lobby badge reader request (MR-2026-0138) is scheduled for May 2.",
      createdAt: "2026-04-26T15:05:00",
      href: "/portal/maintenance/maint-2",
      hrefLabel: "View request",
    },
    {
      id: "notif-10",
      type: "new_announcement",
      category: "Announcements",
      title: "Package room hours updated",
      body: "Lobby package room hours have changed. See the latest announcement.",
      createdAt: "2026-04-22T09:00:00",
      href: "/portal/announcements",
      hrefLabel: "View announcements",
    },
  ];
}
